import { jsPDF } from 'jspdf'
import * as XLSX from 'xlsx'
import type { ArtistRevenue, LabelInfo } from './types'
import type { ProcessedArtistData } from './data-processor'

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat('de-DE', {
    style: 'currency',
    currency: 'EUR',
  }).format(value)
}

export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('de-DE', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(date)
}

export function generatePDF(
  artistData: ProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let yPos = 20

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Statement of Sales', margin, yPos)
  
  yPos += 15
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  if (labelInfo.name) {
    doc.text(labelInfo.name, margin, yPos)
    yPos += 5
  }
  
  if (labelInfo.address) {
    const addressLines = labelInfo.address.split('\n')
    addressLines.forEach((line) => {
      doc.text(line, margin, yPos)
      yPos += 5
    })
  }
  
  yPos += 5
  doc.text(`Generated: ${formatDate(new Date())}`, margin, yPos)
  yPos += 5
  
  if (periodStart && periodEnd) {
    doc.text(`Period: ${periodStart} - ${periodEnd}`, margin, yPos)
    yPos += 10
  } else {
    yPos += 5
  }

  doc.setDrawColor(100, 60, 200)
  doc.setLineWidth(0.5)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 15

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(`Artist: ${artistData.artist}`, margin, yPos)
  yPos += 15

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Revenue Summary', margin, yPos)
  yPos += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  const summaryData = [
    ['Digital Revenue', formatCurrency(artistData.totalDigitalRevenue)],
    ['Physical Revenue', formatCurrency(artistData.totalPhysicalRevenue)],
    ['Manual Revenue', formatCurrency(artistData.manualRevenue)],
    ['Gross Revenue', formatCurrency(artistData.grossRevenue)],
    ['Split Percentage', `${artistData.splitPercentage}%`],
  ]

  summaryData.forEach(([label, value]) => {
    doc.text(label, margin + 5, yPos)
    doc.text(value, pageWidth - margin - 40, yPos, { align: 'right' })
    yPos += 7
  })

  yPos += 3
  doc.setDrawColor(100, 60, 200)
  doc.setLineWidth(0.3)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 7

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Final Payout', margin + 5, yPos)
  doc.text(formatCurrency(artistData.finalPayout), pageWidth - margin - 40, yPos, { align: 'right' })
  yPos += 10

  doc.setDrawColor(100, 60, 200)
  doc.setLineWidth(0.3)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 15

  if (artistData.transactions.length > 0) {
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('Transaction Details', margin, yPos)
    yPos += 8

    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')

    const headers = ['Month', 'Release', 'Track', 'Platform', 'Qty', 'Revenue']
    const colWidths = [20, 45, 45, 30, 15, 25]
    let xPos = margin

    doc.setFont('helvetica', 'bold')
    headers.forEach((header, i) => {
      doc.text(header, xPos, yPos)
      xPos += colWidths[i]
    })
    yPos += 6

    doc.setFont('helvetica', 'normal')

    const maxTransactions = 25
    const displayTransactions = artistData.transactions.slice(0, maxTransactions)

    displayTransactions.forEach((transaction) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }

      xPos = margin
      const rowData = [
        transaction.sales_month || 'N/A',
        transaction.release_title.substring(0, 20),
        transaction.track_title.substring(0, 20),
        transaction.platform.substring(0, 12),
        transaction.quantity.toString(),
        formatCurrency(transaction.net_revenue),
      ]

      rowData.forEach((cell, i) => {
        doc.text(cell, xPos, yPos, { maxWidth: colWidths[i] - 2 })
        xPos += colWidths[i]
      })
      yPos += 5
    })

    if (artistData.transactions.length > maxTransactions) {
      yPos += 5
      doc.setFont('helvetica', 'italic')
      doc.text(
        `... and ${artistData.transactions.length - maxTransactions} more transactions`,
        margin,
        yPos
      )
    }
  }

  yPos = doc.internal.pageSize.getHeight() - 15
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by SOS Generator', pageWidth / 2, yPos, { align: 'center' })

  return doc.output('blob')
}

export function generateExcel(
  artistData: ProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  const workbook = XLSX.utils.book_new()

  const summaryData = [
    ['Statement of Sales'],
    [],
    ['Label', labelInfo.name || 'N/A'],
    ['Address', labelInfo.address || 'N/A'],
    ['Generated', formatDate(new Date())],
    ['Period', periodStart && periodEnd ? `${periodStart} - ${periodEnd}` : 'N/A'],
    [],
    ['Artist', artistData.artist],
    [],
    ['Revenue Summary'],
    ['Category', 'Amount'],
    ['Digital Revenue', artistData.totalDigitalRevenue],
    ['Physical Revenue', artistData.totalPhysicalRevenue],
    ['Manual Revenue', artistData.manualRevenue],
    ['Gross Revenue', artistData.grossRevenue],
    ['Split Percentage', `${artistData.splitPercentage}%`],
    ['Final Payout', artistData.finalPayout],
  ]

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
  
  summarySheet['!cols'] = [{ wch: 25 }, { wch: 30 }]

  if (summarySheet['A1']) {
    summarySheet['A1'].s = {
      font: { bold: true, sz: 16 },
    }
  }

  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')

  if (artistData.transactions.length > 0) {
    const transactionHeaders = [
      'Sales Month',
      'Platform',
      'Country',
      'Release Title',
      'Track Title',
      'UPC/EAN',
      'ISRC',
      'Catalog Number',
      'Quantity',
      'Net Revenue',
      'Currency',
      'Type',
    ]

    const transactionRows = artistData.transactions.map((t) => [
      t.sales_month,
      t.platform,
      t.country,
      t.release_title,
      t.track_title,
      t.upc_ean,
      t.isrc,
      t.catalog_number,
      t.quantity,
      t.net_revenue,
      t.currency,
      t.is_physical ? 'Physical' : 'Digital',
    ])

    const transactionData = [transactionHeaders, ...transactionRows]
    const transactionSheet = XLSX.utils.aoa_to_sheet(transactionData)

    transactionSheet['!cols'] = [
      { wch: 15 },
      { wch: 20 },
      { wch: 15 },
      { wch: 30 },
      { wch: 30 },
      { wch: 15 },
      { wch: 15 },
      { wch: 15 },
      { wch: 10 },
      { wch: 15 },
      { wch: 10 },
      { wch: 10 },
    ]

    XLSX.utils.book_append_sheet(workbook, transactionSheet, 'Transactions')
  }

  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' })
  return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export async function generateZipOfAllStatements(
  artistsData: ProcessedArtistData[],
  labelInfo: LabelInfo,
  format: 'pdf' | 'excel' | 'both' = 'both'
): Promise<Blob> {
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()

  for (const artistData of artistsData) {
    const safeArtistName = artistData.artist.replace(/[^a-z0-9]/gi, '_')

    if (format === 'pdf' || format === 'both') {
      const pdfBlob = generatePDF(artistData, labelInfo)
      zip.file(`${safeArtistName}_statement.pdf`, pdfBlob)
    }

    if (format === 'excel' || format === 'both') {
      const excelBlob = generateExcel(artistData, labelInfo)
      zip.file(`${safeArtistName}_statement.xlsx`, excelBlob)
    }
  }

  return await zip.generateAsync({ type: 'blob' })
}
