import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import type { SafeProcessedArtistData } from '@/lib/types'
import type { LabelInfo } from '@/lib/types'

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat('de-DE', {
    style: 'currency',
    currency: 'EUR',
  }).format(value)
}

export function generatePDF(
  artistData: SafeProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  try {
    return buildPDF(artistData, labelInfo, periodStart, periodEnd)
  } catch (err) {
    throw new Error(
      `PDF generation failed for "${artistData.artist}": ${err instanceof Error ? err.message : String(err)}`
    )
  }
}

function buildPDF(
  artistData: SafeProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  const doc = new jsPDF()
  const margin = 20
  let yPos = margin

  // Add label logo if available
  if (labelInfo.logo) {
    try {
      const logoSize = 25
      const pageWidth = doc.internal.pageSize.getWidth()
      doc.addImage(labelInfo.logo, 'PNG', pageWidth - margin - logoSize, yPos - 5, logoSize, logoSize)
    } catch {
      // Logo rendering failed, continue without it
    }
  }

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  if (labelInfo.name) {
    doc.text(labelInfo.name, margin, yPos)
    yPos += 5
  }
  
  if (labelInfo.address) {
    const addressLines = labelInfo.address.split('\n')
    addressLines.forEach((line) => {
      doc.text(line, margin, yPos)
      yPos += 5
    })
  }
  
  yPos += 5

  if (periodStart && periodEnd) {
    doc.setFontSize(10)
    doc.text(`Period: ${periodStart} - ${periodEnd}`, margin, yPos)
    yPos += 10
  }

  doc.setLineWidth(0.5)
  doc.line(margin, yPos, 190, yPos)
  yPos += 15

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Statement of Sales', margin, yPos)
  yPos += 10

  doc.setFontSize(12)
  doc.text(`Artist: ${artistData.artist}`, margin, yPos)
  yPos += 10

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  const summaryData = [
    ['Digital Revenue', formatCurrency(artistData.totalDigitalRevenue)],
    ['Physical Revenue', formatCurrency(artistData.totalPhysicalRevenue)],
    ['Manual Revenue', formatCurrency(artistData.manualRevenue)],
    ['Gross Revenue', formatCurrency(artistData.grossRevenue)],
    ['Split Percentage', `${artistData.splitPercentage}%`],
    ['Final Payout', formatCurrency(artistData.finalPayout)],
  ]

  summaryData.forEach(([label, value]) => {
    doc.text(label + ':', margin, yPos)
    doc.text(value, margin + 80, yPos)
    yPos += 6
  })

  doc.setLineWidth(0.5)
  doc.line(margin, yPos, 190, yPos)
  yPos += 10

  // ── Release breakdown ─────────────────────────────────────────────────────
  // autoTable handles pagination automatically — no slice() or manual yPos math needed.
  autoTable(doc, {
    startY: yPos,
    head: [['Release Title', 'Revenue', 'Qty', 'Type']],
    body: artistData.releaseBreakdown.map(rel => [
      rel.releaseTitle || '-',
      formatCurrency(rel.revenue),
      String(rel.quantity),
      rel.isPhysical ? 'Physical' : 'Digital',
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [40, 40, 60], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' },
    },
    margin: { left: margin, right: margin },
    didDrawPage: (data) => {
      const pageCount = (doc as jsPDF & { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
      const pageNumber = data.pageNumber
      const pageHeight = doc.internal.pageSize.getHeight()
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by SOS Generator', margin, pageHeight - 8)
      doc.text(`Page ${pageNumber} of ${pageCount}`, doc.internal.pageSize.getWidth() - margin, pageHeight - 8, { align: 'right' })
    },
  })

  // ── Platform breakdown ────────────────────────────────────────────────────
  if (artistData.platformBreakdown.length > 0) {
    const afterReleases = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8
    autoTable(doc, {
      startY: afterReleases,
      head: [['Platform', 'Revenue', 'Qty']],
      body: artistData.platformBreakdown.map(p => [
        p.platform || 'Unknown',
        formatCurrency(p.revenue),
        String(p.quantity),
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [40, 40, 60], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
      },
      margin: { left: margin, right: margin },
      didDrawPage: (data) => {
        const pageCount = (doc as jsPDF & { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
        const pageNumber = data.pageNumber
        const pageHeight = doc.internal.pageSize.getHeight()
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        doc.text('Generated by SOS Generator', margin, pageHeight - 8)
        doc.text(`Page ${pageNumber} of ${pageCount}`, doc.internal.pageSize.getWidth() - margin, pageHeight - 8, { align: 'right' })
      },
    })
  }

  return doc.output('blob')
}

export function generateExcel(
  artistData: SafeProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  try {
    return buildExcel(artistData, labelInfo, periodStart, periodEnd)
  } catch (err) {
    throw new Error(
      `Excel generation failed for "${artistData.artist}": ${err instanceof Error ? err.message : String(err)}`
    )
  }
}

function buildExcel(
  artistData: SafeProcessedArtistData,
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string
): Blob {
  const workbook = XLSX.utils.book_new()

  const summaryData = [
    ['Statement of Sales'],
    [],
    ['Label', labelInfo.name || ''],
    ['Address', labelInfo.address || ''],
    [],
    ['Artist', artistData.artist],
    ['Period', periodStart && periodEnd ? `${periodStart} - ${periodEnd}` : ''],
    [],
    ['Revenue Summary'],
    ['Believe Revenue', artistData.believeRevenue],
    ['Bandcamp Revenue', artistData.bandcampRevenue],
    ['Digital Revenue', artistData.totalDigitalRevenue],
    ['Physical Revenue', artistData.totalPhysicalRevenue],
    ['Manual Revenue', artistData.manualRevenue],
    ['Gross Revenue', artistData.grossRevenue],
    ['Split Percentage', artistData.splitPercentage / 100],
    ['Final Payout', artistData.finalPayout],
  ]

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
  summarySheet['!cols'] = [{ wch: 25 }, { wch: 25 }]

  if (summarySheet['A1']) {
    summarySheet['A1'].s = { font: { bold: true, sz: 14 } }
  }

  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')

  // Release breakdown sheet (aggregated, memory-efficient alternative to raw rows)
  if (artistData.releaseBreakdown.length > 0) {
    const releaseHeaders = [
      'Release Title', 'UPC/EAN', 'Catalog Number', 'Revenue', 'Quantity', 'Type',
    ]
    const releaseRows = artistData.releaseBreakdown.map(r => [
      r.releaseTitle || '',
      r.upcEan || '',
      r.catalogNumber || '',
      r.revenue,
      r.quantity,
      r.isPhysical ? 'Physical' : 'Digital',
    ])
    const releaseSheet = XLSX.utils.aoa_to_sheet([releaseHeaders, ...releaseRows])
    releaseSheet['!cols'] = [
      { wch: 35 }, { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 10 }, { wch: 10 },
    ]
    XLSX.utils.book_append_sheet(workbook, releaseSheet, 'Releases')
  }

  // Platform breakdown sheet
  if (artistData.platformBreakdown.length > 0) {
    const platformHeaders = ['Platform', 'Revenue', 'Quantity']
    const platformRows = artistData.platformBreakdown.map(p => [
      p.platform || 'Unknown', p.revenue, p.quantity,
    ])
    const platformSheet = XLSX.utils.aoa_to_sheet([platformHeaders, ...platformRows])
    platformSheet['!cols'] = [{ wch: 25 }, { wch: 15 }, { wch: 10 }]
    XLSX.utils.book_append_sheet(workbook, platformSheet, 'Platforms')
  }

  // Country breakdown sheet
  if (artistData.countryBreakdown.length > 0) {
    const countryHeaders = ['Country', 'Revenue', 'Quantity']
    const countryRows = artistData.countryBreakdown.map(c => [
      c.country || 'Unknown', c.revenue, c.quantity,
    ])
    const countrySheet = XLSX.utils.aoa_to_sheet([countryHeaders, ...countryRows])
    countrySheet['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 10 }]
    XLSX.utils.book_append_sheet(workbook, countrySheet, 'Countries')
  }

  // Monthly breakdown sheet
  if (artistData.monthlyBreakdown.length > 0) {
    const monthHeaders = ['Month', 'Revenue']
    const monthRows = artistData.monthlyBreakdown.map(m => [m.month, m.revenue])
    const monthSheet = XLSX.utils.aoa_to_sheet([monthHeaders, ...monthRows])
    monthSheet['!cols'] = [{ wch: 12 }, { wch: 15 }]
    XLSX.utils.book_append_sheet(workbook, monthSheet, 'Monthly')
  }

  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' })
  return new Blob([excelBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
}

/** Downloads a Blob as a file. Revokes the object URL after a short delay so
 *  the browser has time to initiate the download before the reference is freed. */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  setTimeout(() => URL.revokeObjectURL(url), 100)
}

/**
 * Generates a ZIP of PDF and/or Excel statements for all artists.
 *
 * Artists are processed sequentially (one per event-loop turn via
 * `setTimeout(0)` yields) so that:
 *  1. The browser UI remains fully responsive during a large export.
 *  2. Memory consumption stays bounded — only one artist's document is live
 *     at a time before it is handed off to JSZip.
 *
 * @param onProgress  Optional callback fired after each artist is processed.
 *                    Receives (done, total) so callers can show a progress bar.
 */
export async function generateZipOfAllStatements(
  artistsData: SafeProcessedArtistData[],
  labelInfo: LabelInfo,
  periodStart?: string,
  periodEnd?: string,
  format: 'pdf' | 'excel' | 'both' = 'both',
  onProgress?: (done: number, total: number) => void
): Promise<Blob> {
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()
  const total = artistsData.length

  for (let i = 0; i < artistsData.length; i++) {
    const artistData = artistsData[i]

    // Yield to the event loop so the main thread can paint progress updates
    // and remain interactive between each document generation.
    await new Promise<void>(resolve => setTimeout(resolve, 0))

    const safeArtistName = artistData.artist.replace(/[^a-z0-9]/gi, '_')

    if (format === 'pdf' || format === 'both') {
      const pdfBlob = generatePDF(artistData, labelInfo, periodStart, periodEnd)
      zip.file(`${safeArtistName}_statement.pdf`, pdfBlob)
    }

    if (format === 'excel' || format === 'both') {
      const excelBlob = generateExcel(artistData, labelInfo, periodStart, periodEnd)
      zip.file(`${safeArtistName}_statement.xlsx`, excelBlob)
    }

    onProgress?.(i + 1, total)
  }

  return await zip.generateAsync({ type: 'blob' })
}
